### ISSUE TITLE
What's the difference

### ISSUE THREAD

**Issue by macmichael01** [1000ch/atom-csscomb#1]
What's the difference between your codebase and this one?
https://github.com/jchouse/csscomb-atom

It really adds to confusion on which one to use when doing a search in atom's package manager. Could these get merged somehow?

**Comment by schiz0p** [comment]
ctrl+c might not be the most convenient keyboard shortcut to define as the default.

**Comment by 1000ch** [comment]
@macmichael01 @schiz0p 
Certainly dups, but this one is continuously maintained by me.
Please send feedbacks more if you noticed something about this.
Thank you.
