### ISSUE TITLE
space-before-combinator is not working

### ISSUE THREAD

**Issue by glrodasz** [1000ch/atom-csscomb#11]
I have the property in this way and is not working:

"space-before-combinator": " "

**Comment by glrodasz** [comment]
Any updates for this?

**Comment by 1000ch** [comment]
@Garethderioth 

Oops, sorry for delay.

This plugin formats CSS after sorting. (So this is not a problem for csscomb.)
I use [perfectionist](https://github.com/ben-eb/perfectionist) for formatting CSS, and it doesn't have an option to insert a space before combinator.
