### ISSUE TITLE
Scss commenting out a property with //

### ISSUE THREAD

**Issue by bpurdyiv** [1000ch/atom-csscomb#14]
I am getting an error when if I have a property commented out using //

The error is "CssSyntaxError", reason: "Unknown word"

**Comment by 1000ch** [comment]
`//` is invalid comment syntax in CSS.
https://developer.mozilla.org/docs/Web/CSS/Comments

**Comment by bpurdyiv** [comment]
Yes, but it is valid SCSS. 
http://sass-lang.com/documentation/file.SCSS_FOR_SASS_USERS.html
