### ISSUE TITLE
Indent size vs csscomb block-indent

### ISSUE THREAD

**Issue by jeroenverfallie** [1000ch/atom-csscomb#18]
Why does the `Indent Size` option in the plugin override the csscomb `block-indent` option?
This makes working on projects with different configs tedious, and creates inconsistencies in teams.

https://github.com/csscomb/csscomb.js/blob/master/doc/options.md#block-indent

**Comment by 1000ch** [comment]
Indeed. Now, options are from [senchalabs/cssbeautify](https://github.com/senchalabs/cssbeautify).
`Indent Size` should be overridden by `block-indent` option of CSScomb if it exists.

**Comment by anselmh** [comment]
Regarding indent size, it seems that it does not respect `.editorconfig`’s indent size. Is that intentional? Should I rather open a new issue for that topic?

**Comment by 1000ch** [comment]
@jeroenverfallie Fixed in `v2.0.0`.
@anselmh Indent Size is provided as option by CSSComb, so it should be configured with `.csscomb.json`?
