### ISSUE TITLE
Add a new rule for Scss/Sass newlineBetweenSelectors 

### ISSUE THREAD

**Issue by tomagladiator** [1000ch/atom-csscomb#19]
Hello,
Thanks for this plugin, 

Can we add this useful rule for SCSS ? 
// Add a new line between selectors
**newlineBetweenSelectors: false!true**

```
//  before
[♥-component~="accordion"] {
    border-bottom: 1px solid $mine-shaft;
    .a--title {
        align-items: center;
        &:hover,
        &:focus {
            cursor: pointer;
        }
        &.isClose {
            &:before {
                @include triangle(20px, $alto, down);
            }
        }
    }
}

// after
[♥-component~="accordion"] {
    border-bottom: 1px solid $mine-shaft;

    .a--title {
        align-items: center;

        &:hover,
        &:focus {
            cursor: pointer;
        }

        &.isClose {
            &:before {
                @include triangle(20px, $alto, down);
            }
        }
    }
}
```

Thanks

**Comment by 1000ch** [comment]
I think it's useful, too.

But this plugin uses [ben-eb/perfectionist](https://github.com/ben-eb/perfectionist) as formatter, so your proposal have to be implemented in it ;)

**Comment by 1000ch** [comment]
It's configurable as CSSComb option, [lines-between-rulesets](https://github.com/csscomb/csscomb.js/blob/master/doc/options.md#lines-between-rulesets).
