### ISSUE TITLE
Small issue with brackets

### ISSUE THREAD

**Issue by brunowego** [1000ch/atom-csscomb#2]
I get small issue when csscomb the css, see below the original CSS:

```
.cities {
  line-height: 36px;
  ul {
    margin-bottom: 0;
  }
  img {
    @extend .img-rounded;
    @extend .img-responsive;
  }
}
```

After comb:

```
.cities {
  line-height: 36px;
  ul {
    margin-bottom: 0;
}
  img {
    @extend .img-rounded;
    @extend .img-responsive;
}
}
```

All brackets going to left. Have a way to fix it? Thanks!

**Comment by brunowego** [comment]
Ops, I use SASS :+1:

**Comment by 1000ch** [comment]
Umm, I think it's problem of CSSComb self. To solve it...
- Apply auto-formatting after comb.
- Report as problem on [CSSComb.js](https://github.com/csscomb/csscomb.js)

**Comment by brunowego** [comment]
Ok, thanks!
