### ISSUE TITLE
fallbacks

### ISSUE THREAD

**Issue by robinknaapen** [1000ch/atom-csscomb#20]
It's recommended that a color that uses rgba() (or any other modern way to define colors) have a fallback color a solid one to be exact, but when i comb my CSS, it'll  put the fallback color under the rgba() color
`color: #212121; color: rgba(0,0,0,87);`

expected output should be that the solid hex code be above the rgba one;

you can check here for more details: https://github.com/CSSLint/csslint/wiki/Require-fallback-colors

**Comment by 1000ch** [comment]
Should be discussed on [csscomb/csscomb.js](https://github.com/csscomb/csscomb.js) itself, not on this repo 👍
