### ISSUE TITLE
Use the `atom-workspace` tag instead of the `workspace` class.

### ISSUE THREAD

**Issue by dylarcher** [1000ch/atom-csscomb#3]
In keymaps\csscomb.cson: Use the `atom-workspace` tag instead of the `workspace` class.

**Comment by 1000ch** [comment]
@darcher- 
Sorry for delay. This problem is fixed with this commit.
https://github.com/1000ch/atom-csscomb/commit/d598e550a6a79d69bbbd976e6c46085a7ba46564
Thank you.
