### ISSUE TITLE
Package update never ends

### ISSUE THREAD

**Issue by franverona** [1000ch/atom-csscomb#8]
Hello,

I'm trying to update CSScomb on my Atom.io editor, but update never ends. This is happening since last update.

Any clues?

Regards,

Fran

**Comment by 1000ch** [comment]
@franverona Does the problem occur constantly?
I could install and uninstall `atom-csscomb` constantly with Atom `1.0.2`.

BTW, If you don't update your Atom yet, I recommend you to update it.

**Comment by franverona** [comment]
That was the problem. I updated my Atom, and all packages (including yours) were updated sucessfully.

**Comment by 1000ch** [comment]
:+1:
